ALTER DATABASE [test2] SET TRUSTWORTHY ON;

USE [test2]
GO

DROP FUNCTION IF EXISTS NewGlobalId
go

DROP FUNCTION IF EXISTS GetHeadItems
go

DROP FUNCTION IF EXISTS GetDataItems
go

DROP FUNCTION IF EXISTS ValuesListToTable
go

DROP FUNCTION IF EXISTS ObjListToTable
go

DROP FUNCTION IF EXISTS CalcRefCount
go

DROP AGGREGATE IF EXISTS ValuesToList
go

DROP AGGREGATE IF EXISTS ObjToList
go

DROP TYPE IF EXISTS IfcValue
go

DROP TYPE IF EXISTS IfcObj 
go

DROP TYPE IF EXISTS IfcFile 
go

DROP ASSEMBLY IF EXISTS [IFCSQL] 
go

-- Import the assembly
CREATE ASSEMBLY [IFCSQL]
FROM 'E:\git_hub\IFCSQL\IFCSQL\bin\Debug\IFCSQL.dll'
WITH PERMISSION_SET = UNSAFE;
go

CREATE TYPE IfcValue 
EXTERNAL NAME [IFCSQL].[IfcValue];  
GO  

CREATE TYPE IfcObj 
EXTERNAL NAME [IFCSQL].[IfcObj];  
GO  

CREATE TYPE IfcFile 
EXTERNAL NAME [IFCSQL].[IfcFile];  
GO  

CREATE FUNCTION [dbo].[GetHeadItems](@wfile [IfcFile])
RETURNS  TABLE ([obj] IfcObj) WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [IFCSQL].[Functions].[GetHeadItems]
GO

CREATE FUNCTION [dbo].[GetDataItems](@wfile [IfcFile])
RETURNS  TABLE ([obj] IfcObj) 
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [IFCSQL].[Functions].[GetDataItems]
GO

CREATE FUNCTION [dbo].[ValuesListToTable](@wlist IfcValue)
RETURNS  TABLE ([obj] IfcValue) 
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [IFCSQL].[Functions].[ValuesListToTable]
GO

CREATE FUNCTION [dbo].[ObjListToTable](@wlist IfcValue)
RETURNS  TABLE ([obj] IfcObj) 
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [IFCSQL].[Functions].[ObjListToTable]
GO

CREATE FUNCTION [dbo].[CalcRefCount](@tablename nvarchar(max), @fieldname nvarchar(max))
RETURNS  TABLE (oid int, refs IfcValue) 
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [IFCSQL].[Functions].[CalcRefCount]
GO

CREATE FUNCTION [dbo].[NewGlobalId]()
RETURNS NVARCHAR(22)
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [IFCSQL].[Functions].[NewGlobalId]
GO

CREATE AGGREGATE ValuesToList (@input IfcValue) RETURNS IfcValue
EXTERNAL NAME [IFCSQL].ValuesToList;  

CREATE AGGREGATE ObjToList (@input IfcObj) RETURNS IfcValue
EXTERNAL NAME [IFCSQL].ObjToList;  